[build]
  command = "npm install && npm run generate"
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/genereerd/data/*.json"
  [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "/kandidaten/:slug.html"
  to = "/genereerd/kandidaten/:slug.html"
  status = 200 

[[redirects]]
  from = "/nieuws/:slug.html"
  to = "/genereerd/nieuws/:slug.html"
  status = 200