backend:
  name: git-gateway
  repo: jok3rboyy/VVD-Wageningen # CONTROLEER DIT! Is dit de juiste repo?
  branch: main

# Zorg dat deze paden kloppen t.o.v. de root van je repository!
media_folder: "images/uploads" # Waarschijnlijk zonder "VVD-Wageningen/" ervoor
public_folder: "/images/uploads" # Het URL pad naar de media

# Vul hier de correcte URL in
site_url: https://vvdwageningen.netlify.app # Of je dev URL

# Content Collections
collections:
  - name: "actueel"
    label: "Actueel"
    folder: "nieuws" # Waarschijnlijk zonder "VVD-Wageningen/" ervoor
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" } # Voor weergave & slug
      - { label: "Publicatiedatum", name: "date", widget: "datetime" }
      - {
          label: "Categorie",
          name: "category",
          widget: "select",
          options: ["raadswerk", "opinie", "agenda", "aankondiging"],
          required: false, # Maak optioneel als niet altijd nodig
        }
      - {
          label: "Thumbnail Afbeelding", # Duidelijker label
          name: "thumbnail", # Naam gebruikt in script
          widget: "image",
          required: false,
        }
      - {
          label: "Korte Samenvatting (excerpt)", # Duidelijker label & naam
          name: "excerpt", # Naam gebruikt in script voor index
          widget: "text",
          required: false, # Maak optioneel
        }
      - { label: "Volledige Inhoud", name: "body", widget: "markdown" } # 'body' is standaard voor hoofdinhoud

  - name: "kandidaten"
    label: "Kandidaten"
    folder: "kandidaten" # Waarschijnlijk zonder "VVD-Wageningen/" ervoor
    create: true
    slug: "{{slug}}" # Wordt meestal afgeleid van het 'naam' veld
    fields:
      # --- !! BELANGRIJK: Keys aangepast aan script/MD !! ---
      - { label: "Volledige Naam", name: "naam", widget: "string" } # Key = naam
      - { label: "Functie/Rol", name: "rol", widget: "string" } # Key = rol
      - {
          label: "Volgorde (Lijstnummer)", # Duidelijker label
          name: "volgorde", # Key = volgorde
          widget: "number",
          value_type: "int", # Zorg dat het een integer is
          min: 1,
          default: 99,
        }
      - { label: "Foto", name: "foto", widget: "image" } # Key = foto
      # --- Einde belangrijke aanpassingen ---
      - {
          label: "E-mailadres",
          name: "email",
          widget: "string",
          required: false,
        }
      - {
          label: "LinkedIn URL",
          name: "linkedin",
          widget: "string",
          required: false,
        }
      - {
          label: "Twitter/X URL",
          name: "twitter",
          widget: "string",
          required: false,
        }
      - {
          label: "Instagram URL",
          name: "instagram",
          widget: "string",
          required: false,
        }
      - {
          label: "Facebook URL",
          name: "facebook",
          widget: "string",
          required: false,
        }
      - {
          label: "Persoonlijke Website URL",
          name: "website",
          widget: "string",
          required: false,
        }
      - {
          label: "Korte Biografie (voor lijst)", # Optioneel voor JSON
          name: "bio_kort",
          widget: "string",
          required: false,
        }
      - {
          label: "Volledige Biografie/Tekst", # Voor eventuele detailpagina
          name: "body", # Hernoemd van 'bio' naar 'body' voor consistentie
          widget: "markdown",
          required: false,
        }
